server:
  port: 8401

spring:
  application:
    name: nacos-sentinel8401
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.120.125:1111 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'


